import { useForm } from "react-hook-form";

import FormGrid from "../../components/form/FormGrid";

import Button from "../../components/ui/button/Button";

import {
    useGenerateDelivery,
    useDeliveryGenerationStatus,
} from  "../../queries/useDeliveryPlanning";
import DateField from "../../components/form/form-input/DateField";

export default function GenerateDeliveryTab() {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);

    const tomorrowDate = tomorrow.toISOString().split("T")[0];

    const { control, watch, handleSubmit } = useForm({
        defaultValues: {
            deliveryDate: tomorrowDate,
        },
    });

    const deliveryDate = watch("deliveryDate");

    const generateMutation = useGenerateDelivery();

    const { data: status, isLoading } =
        useDeliveryGenerationStatus(deliveryDate);

    const onSubmit = async (data) => {
        if (
            status?.isGenerated &&
            !window.confirm(
                "Delivery is already generated.\n\nDo you want to regenerate?"
            )
        ) {
            return;
        }

        await generateMutation.mutateAsync({
            deliveryDate: data.deliveryDate,
        });
    };

    return (
        <div className="space-y-6">
            {/* Generate */}

            <div className="rounded-xl border border-gray-200 bg-white p-6">
                <form onSubmit={handleSubmit(onSubmit)}>
                    <FormGrid cols={4} gap={4}>
                        <DateField
                            control={control}
                            name="deliveryDate"
                            label="Delivery Date"
                            disabled
                        />

                        <div className="flex items-end">
                            <Button
                                type="submit"
                                loading={generateMutation.isPending}
                                className="w-full"
                            >
                                {status?.isGenerated
                                    ? "Regenerate Delivery"
                                    : "Generate Delivery"}
                            </Button>
                        </div>
                    </FormGrid>
                </form>
            </div>

            {/* Status */}

            <div className="rounded-xl border border-gray-200 bg-white p-5">
                <h3 className="mb-4 text-lg font-semibold">
                    Delivery Status
                </h3>

                {isLoading ? (
                    <p className="text-sm text-gray-500">
                        Loading...
                    </p>
                ) : !status?.isGenerated ? (
                    <div className="rounded-lg border border-red-200 bg-red-50 p-4">
                        <p className="font-semibold text-red-700">
                            ❌ Delivery not generated.
                        </p>

                        <p className="mt-1 text-sm text-red-600">
                            Click Generate Delivery to create tomorrow's
                            delivery details.
                        </p>
                    </div>
                ) : (
                    <div className="rounded-lg border border-green-200 bg-green-50 p-4">
                        <p className="font-semibold text-green-700">
                            ✅ Delivery already generated.
                        </p>

                        <div className="mt-3 space-y-2 text-sm text-gray-700">
                            <div className="flex justify-between">
                                <span>Total Deliveries</span>
                                <span className="font-semibold">
                                    {status.totalDeliveries}
                                </span>
                            </div>

                            <div className="flex justify-between">
                                <span>Generated At</span>
                                <span>
                                    {status.generatedAt ?? "-"}
                                </span>
                            </div>

                            <div className="flex justify-between">
                                <span>Generated By</span>
                                <span>
                                    {status.generatedBy ?? "-"}
                                </span>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Warning */}

            <div className="rounded-xl border border-yellow-200 bg-yellow-50 p-4">
                <h4 className="font-semibold text-yellow-800">
                    Warning
                </h4>

                <p className="mt-2 text-sm text-yellow-700">
                    Regenerating deliveries will delete all existing
                    delivery details for the selected date and create
                    them again.
                </p>
            </div>
        </div>
    );
}